---
clusterName: nova
talosVersion: v1.11.5
kubernetesVersion: v1.34.0
endpoint: https://192.168.2.58:6443
allowSchedulingOnMasters: true
nodes:
  - hostname: controlplane
    controlPlane: true
    ipAddress: 192.168.2.58
    installDisk: /dev/sda
    nodeLabels:
      physical-location: nas
  - hostname: workload
    controlPlane: false
    ipAddress: 192.168.2.202
    installDisk: /dev/sda
    nodeLabels:
      physical-location: nas
