---
clusterName: hypnos
talosVersion: v1.11.5
kubernetesVersion: v1.34.0
endpoint: https://192.168.2.208:6443
allowSchedulingOnMasters: true
nodes:
  - hostname: master
    controlPlane: true
    ipAddress: 192.168.2.208
    installDisk: /dev/sda
    nodeLabels:
      physical-location: nas
  - hostname: workload
    controlPlane: false
    ipAddress: 192.168.2.29
    installDisk: /dev/sda
    nodeLabels:
      physical-location: nas
